export const languages = {
    english: {
        hello: 'hello',
        login_title1: 'Sign in to be',
        register_title1: 'Register to be',
        register_title2: 'always upto date',
        your_email: 'Your email',
        your_password: 'Your password',
        confirm_password: 'Confirm password',
        register_now: 'Register Now',
        //without_reg: 'Continue Without Registration',
        search: 'Search',
        concerts: 'Concerts',
        festivals: 'Festival',
        theater: 'Theater',
        for_children: 'For children',
        live: 'LIVE',
        now_on_air: 'Now on air',
        setting_panel: 'Setting panel',
        profile: 'Profile',
        notification: 'Notification',
        artist_vol: 'Artist Volume',
        audience_vol: 'Audience volume',
        dark_mode: 'Dark mode',
        language: 'Language',
        privacy: 'Privacy',
        help: 'Help',
        log_out: 'Log Out',
        on: 'On',
        off: 'Off',
        video_formats: 'Video is available in',
        video_formats1: 'formats',
        watch_now: 'Watch Now',
        disable_aud: 'Disable audience interaction',
        message: 'Message',
        login: 'Sign in',
        without_reg: 'Continue Without Sign in',
        dont_have_account: `Don't have Account? Register`,
        have_account: `Have an account? Sign In`,
        emailEmpty: 'Email can not be empty',
        emialFormat: 'Email format is invalid',
        passwordLength: 'password should be atleast 6 characters',
        passwordNotMatch: 'password not matched!',
        userAlreadyExist: 'email already exist',
        register_done: 'Your account has been created',
        login_fail: 'Email or password is invalid',
        no_events: 'No events found of this type!',
        no_types: 'No event types found!'
        
    },
    franch: {
        hello: 'hello',
        login_title1: `S'identifier pour être`,
        register_title1: 'Inscrivez-vous pour être',
        register_title2: 'toujours à jour',
        your_email: 'Votre e-mail',
        your_password: 'Votre mot de passe',
        confirm_password: 'Confirmez le mot de passe',
        register_now: `S'inscrire maintenant`,
        without_reg: 'Continuer sans inscription',
        search: 'Chercher',
        concerts: 'Concerts',
        festivals: 'Festival',
        theater: 'Théâtre',
        for_children: 'Pour les enfants',
        live: 'HABITENT',
        now_on_air: `Maintenant à l'antenne`,
        setting_panel: 'Panneau de réglage',
        profile: 'Profil',
        notification: 'Notification',
        artist_vol: `Volume de l'artiste`,
        audience_vol: `Volume d'audience`,
        dark_mode: 'Mode sombre',
        language: 'Langue',
        privacy: 'Intimité',
        help: 'Aider',
        log_out: 'Se déconnecter',
        on: 'au',
        off: 'Désactivé',
        video_formats: 'La vidéo est disponible en',
        video_formats1: 'formats',
        watch_now: 'Regarde maintenant',
        disable_aud: `Désactiver l'interaction avec l'audience`,
        message: 'Un message',
        login: `S'identifier`,
        without_reg: `Continue Without S'identifier`,
        dont_have_account: `Vous n'avez pas de compte ? S'inscrire`,
        have_account: `Avoir un compte? S'identifier`,
        emailEmpty: `L'e-mail ne peut pas être vide`,
        emialFormat: `Le format de l'e-mail n'est pas valide`,
        passwordLength: `le mot de passe doit comporter au moins 6 caractères`,
        passwordNotMatch: 'le mot de passe ne correspond pas !',
        userAlreadyExist: `l'email existe déjà`,
        register_done: `Votre compte a été créé`,
        login_fail: `L'email ou le mot de passe est invalide`,
        no_events: 'Aucun événement trouvé de ce type !',
        no_types: `Aucun type d'événement trouvé !`,
    }
}